# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 21:27
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Corpus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
                ('author', models.CharField(max_length=300)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('period', models.CharField(choices=[('Pre-Romantic', 'Pre-Romantic'), ('Romantic', 'Romantic'), ('Victorian', 'Victorian')], max_length=30)),
                ('mode', models.CharField(choices=[('Drama', 'Drama'), ('Fragment', 'Fragment'), ('Novel', 'Novel'), ('Poetry', 'Poetry'), ('Review', 'Review'), ('Serial Novel', 'Serial Novel'), ('Short Story', 'Short Story'), ('Short Story Collection', 'Short Story Collection'), ('Theory & Criticism', 'Theory & Criticism')], max_length=30)),
                ('genre', models.CharField(choices=[('Ballad', 'Ballad'), ('Tragedy', 'Tragedy')], max_length=30)),
                ('nationality', models.CharField(choices=[('American', 'American'), ('Canadian', 'Canadian'), ('English', 'English'), ('French', 'French'), ('German', 'German')], max_length=30)),
                ('pseudonym', models.CharField(blank=True, max_length=75, null=True)),
                ('role', models.CharField(choices=[('Central', 'Central'), ('Influence', 'Influence'), ('Peripheral', 'Peripheral')], max_length=30)),
                ('authority', models.CharField(blank=True, max_length=150, null=True)),
                ('filename', models.CharField(max_length=150)),
                ('full_text_source', models.URLField(blank=True, null=True)),
                ('illustrator', models.CharField(blank=True, max_length=300, null=True)),
                ('translator', models.CharField(blank=True, max_length=300, null=True)),
                ('ebook_source', models.URLField(blank=True, null=True)),
                ('more_info', models.URLField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, max_length=1000, null=True)),
                ('etext_publisher', models.CharField(blank=True, max_length=200, null=True)),
                ('ebook_num', models.CharField(max_length=300)),
                ('etext_pub_date', models.CharField(blank=True, max_length=30, null=True)),
                ('date_accessed', models.CharField(blank=True, max_length=30, null=True)),
                ('editor', models.CharField(blank=True, max_length=300, null=True)),
                ('edition', models.CharField(blank=True, max_length=300, null=True)),
                ('date_added', models.DateField(auto_now_add=True)),
                ('cover_art', models.URLField(blank=True, null=True)),
                ('color_data', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
            ],
        ),
    ]
