# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-30 22:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gothiccolors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('first_usage', models.IntegerField(blank=True, null=True)),
                ('family', models.CharField(max_length=100)),
                ('hex_value', models.CharField(max_length=10, null=True)),
                ('image_url', models.URLField(null=True)),
            ],
        ),
    ]
