# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-06 22:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gothiccolors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
