# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-12 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gothiccolors', '0002_corpus_word_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corpus',
            name='word_count',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
