# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-07 05:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gothiccolors', '0002_auto_20170506_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='corpus',
            name='color_data',
        ),
        migrations.AddField(
            model_name='corpus',
            name='color_dict',
            field=models.CharField(blank=True, max_length=15000, null=True),
        ),
        migrations.AddField(
            model_name='corpus',
            name='color_list',
            field=models.CharField(blank=True, max_length=15000, null=True),
        ),
    ]
